# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36fc681ea11fbc0e16d1b30101c4bc461148a4648b4c65a7ceb613ceb1cfaa1f719e9bcbf6a3bd000d20956d73f12514a97b6f93f11124763cc7bbe8988b8c1f

test:
  secret_key_base: 245f6300e373bd06e0648e24c915207efcdc7dc9f36bc17de4f0188f733aeecdb947ed7f4ebaf52682be6c5f140772e458ff013969f053ac4697451c4d91134c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
